model:
  target: model_managment.models.UltraLidarModel
  base_learning_rate: 2.0e-3
  params:
    codebook:
      target: model_managment.codebooks.VectorQuantizer
      params:
        n_embed: 1024
        embed_dim: 1024
        beta: 0.25
        cosine_similarity: false
        rearrange: false

    voxelizer:
      target: data_managment.voxelize.Voxelizer
      params:
        x_min: 2.7
        x_max: 162.7
        y_min: -48
        y_max: 48
        z_min: -2
        z_max: 18
        step: 0.5
        z_step: 0.2
        fov: 2.268
      mode: 'linear'

    patch_size: 8
dataset:
  filter_fov: false
